### ISSUE TITLE
xlink:href support

### ISSUE THREAD

**Issue by brunnolou** [alexlur/jsx-dom#6]
Hey, thanks for your work!

But this is not working:
```svg
<svg>
    <use xlink:href="#icon-id" />
</svg>
```

This is not being converted:
```svg
<svg>
    <use xlinkHref="#icon-id" />
</svg>
```

Still renders:
<img width="283" alt="screen shot 2017-11-06 at 13 49 53" src="https://user-images.githubusercontent.com/2729225/32444154-79a945ec-c2f9-11e7-8d33-0657ab633ee1.png">

**Comment by alexlur** [comment]
Thanks for the report. Do you have a sample SVG file I can test this with?

**Comment by brunnolou** [comment]
Thanks for the quick reply.
Let me know if it is an easy fix, maybe I could help with a PR.

Here you got:
```html
<body data-gr-c-s-loaded="true">
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position: absolute; width: 0; height: 0">
    <symbol viewBox="0 0 273.4 222.2" id="twitter">
      <path d="M273.4,26.3c-10.1,4.5-20.9,7.5-32.2,8.8c11.6-6.9,20.5-17.9,24.7-31C255,10.5,243,15.2,230.2,17.7
C220,6.8,205.4,0,189.3,0c-31,0-56.1,25.1-56.1,56.1c0,4.4,0.5,8.7,1.5,12.8C88,66.5,46.7,44.2,19,10.3c-4.8,8.3-7.6,17.9-7.6,28.2
c0,19.5,9.9,36.6,25,46.7c-9.2-0.3-17.8-2.8-25.4-7c0,0.2,0,0.5,0,0.7c0,27.2,19.3,49.8,45,55c-4.7,1.3-9.7,2-14.8,2
c-3.6,0-7.1-0.4-10.6-1c7.1,22.3,27.9,38.5,52.4,39c-19.2,15-43.4,24-69.7,24c-4.5,0-9-0.3-13.4-0.8c24.8,15.9,54.3,25.2,86,25.2
c103.2,0,159.6-85.5,159.6-159.6c0-2.4-0.1-4.9-0.2-7.3C256.4,47.4,265.9,37.5,273.4,26.3z" />
    </symbol>
  </svg>

  <svg viewBox="0 0 273.4 222.2">
    <use xlink:href="#twitter"></use>
  </svg>

</body>
```

[Online sample](http://kisenka.me/svg-sprite-loader/examples/server-side-rendering/build/index.html)

**Comment by alexlur** [comment]
Let me know if it fixes your problem.

**Comment by alexlur** [comment]
Try to build the latest version and let me know if it fixes your problem.

**Comment by brunnolou** [comment]
Thanks @alexlur for the quick fix!
Did you forget to add the **build** files to the npm?
Because version `5.1.6` don't include these changes so isn't working.
But I cloned and built myself and copied the `svg.js` and works!

**Comment by alexlur** [comment]
Yes. I don’t want to publish it without confirming that it works.

**Comment by alexlur** [comment]
Published.

**Comment by brunnolou** [comment]
Perfect! 👍  Thank you so much! 🎉 🎈 

Just `jsx-dom` => `jsx-dom/svg` and now it's working 😉

**Comment by Grafikart** [comment]
Do you think you could handle the attributes without the camelcase ? I'm using htm and I do this

```js
htm`<button type="button" onclick=${this.removeCourse}>
    <svg class="icon icon-delete">
        <use xlink:href="/sprite.svg#delete"></use>
    </svg>
</button>
```

And it doesn't work since you expect xlinkHref. It would be nice to handle "native" syntax for attributes (but I totally understand if you don't want it to stick closer to react)

**Comment by proteriax** [comment]
@Grafikart I tested with my editor and apparently having a colon in an attribute name is invalid according to JSX syntax. Unfortunately you will have to file an RFC at [@reactjs/rfcs](https://github.com/reactjs/rfcs) to support this use case.
